title = 'Web de Óscar'
baseURL = 'https://oscmartin56.github.io/paginaHugo/'
defaultContentLanguage = "en-en"
theme = "hugoblog"

[menu]
  [[menu.main]]
    pageRef="/"
    name = "Inicio"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Canales TV"
    url = "/canalestv/"
    weight = 3

  [[menu.main]]
    name = "Amigos"
    url = "/amigos/"
    weight = 2

  [[menu.main]]
    name = "Markdown Basico"
    url = "/markdownBasico/"
    weight = 4
    
  [[menu.main]]
    name = "Markdown Gráficos"
    url = "/markdownGrafico/"
    weight = 5

  [[menu.main]]
    name = "Markdown Extendido"
    url = "/markdownExtendido/"
    weight = 6

  [[menu.main]]
    name = "Java"
    url = "/java/"
    weight = 7