# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    # Clono el repositorio
      - name: Checkout
        uses: actions/checkout@v4
# Instalo hugo
      - name: Setup Hugo
        run: |
          sudo apt-get update
          sudo apt-get install hugo -y
# Clono el repositorio
      - name: build hugo site
        run: hugo --minify
# Subir el contenido general a GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: action/upload-pages-artifact@v3
        with:
         #solo los ficheros generados en ./public
           path: './public'
      - name: deploy to github pages
        id: deployment
        uses: action/deply-pages@v4
     
