# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Instalar Hugo
      - name: Setup Hugo
        run: |
          sudo apt-get update
          sudo apt-get install hugo -y

      # 3. Construir el sitio desde el subdirectorio paginaOscar
      - name: Build Hugo Site
        working-directory: ./paginaOscar
        run: hugo --minify

      # 4. Configurar GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 5. Subir el contenido generado en paginaOscar/public
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./paginaOscar/public

      # 6. Desplegar a GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
